### ISSUE TITLE
[Feature Request] More components and utilities.

### ISSUE THREAD

**Issue by TokenChingy** [erenesto/gralig#1]
This is a beautiful library you have made. I've already used it in one project and it's great. A few things I would like to see:

- A sectional component for content, that has size modifiers.
- The offscreen menu you have on the Gralig website.
- Padding and margin utilities.

Other than that, it seems really awesome!

**Comment by erenesto** [comment]
Hi @TokenChingy,

Thank you for your positive comments. I added the features you specified to my to-do list. 👍
